package my.adridanrakanrakan;
/**
 *
 * @author akifrabbani
 */

//import java.io.FileReader;
//import java.util.Iterator;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.FileWriter; 
import java.io.IOException;

//import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import org.apache.commons.io.IOUtils;
import java.util.*; 

import java.awt.*;
//import java.awt.event.*;
//import javax.swing.*;

import javax.swing.JOptionPane;
//import java.sql.Timestamp; 

public class CreateImportClass extends javax.swing.JFrame {

    
    public int current_sale_id = 0;
    int mode = 1;
    double hausboom = 2.00;
    public String finalP = "";
    public JSONObject data = new JSONObject();
    public CreateImportClass() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        filePathDisplay = new javax.swing.JTextField();
        locateFile = new javax.swing.JButton();
        continueBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create / Import Quotation");
        setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Cancel");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        exitBtn.setContentAreaFilled(false);
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Welcome to Hausboom Cafe!");

        jLabel2.setText("Please choose if you want to load existing config file or create a new one.");

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setLabel("Create new config file");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setLabel("Load existing config file");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        filePathDisplay.setEditable(false);
        filePathDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        locateFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        locateFile.setContentAreaFilled(false);
        locateFile.setEnabled(false);
        locateFile.setLabel("...");
        locateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateFileActionPerformed(evt);
            }
        });

        continueBtn.setBackground(new java.awt.Color(255, 255, 255));
        continueBtn.setText("Continue");
        continueBtn.setToolTipText("");
        continueBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        continueBtn.setContentAreaFilled(false);
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/Hausboom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(filePathDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(locateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locateFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        locateFile.setEnabled(false);
        filePathDisplay.setText("");
        continueBtn.setEnabled(true);
        mode = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        locateFile.setEnabled(true);
        continueBtn.setEnabled(false);
        mode = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void locateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateFileActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.LOAD);
        fd.setDirectory(System.getProperty("user.home"));
//        fd.setFile("*.json");
        fd.setVisible(true);
        String filename = fd.getFile();
        if (filename == null) {
          continueBtn.setEnabled(false);
          filePathDisplay.setText("");
          System.out.println("You cancelled the choice");
        } else {
          continueBtn.setEnabled(true);
          String filePath = fd.getDirectory() + fd.getFile();
          finalP = filePath;
          System.out.println("You chose " + filePath);
          filePathDisplay.setText(filePath);
          
        }
    }//GEN-LAST:event_locateFileActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
        //dispose();
    }//GEN-LAST:event_exitBtnActionPerformed
    
    public boolean saveChanges() {
        try {    
    
            FileWriter fw = new FileWriter(finalP);    
            fw.write(data.toString());    
            fw.close();  
        } catch(IOException e) { //Exception
            System.out.println(e);
            return false;
        }
            File f = new File(finalP);
            if (f.exists()){
                 try
                {
                    InputStream is = new FileInputStream(finalP);
                    String jsonTxt = IOUtils.toString(is, "UTF-8");
                    JSONParser parser = new JSONParser();
                    Object obj = parser.parse(jsonTxt);
                    data = (JSONObject) obj;
                }    catch (Exception ex)  
                {
                    // insert code to run when exception occurs
                    JOptionPane.showMessageDialog(null, "Invalid data file.", "Oops", JOptionPane.ERROR_MESSAGE);
                }
                 
                current_sale_id = ((Long) data.get("current_sale_id")).intValue();
                System.out.println(current_sale_id);
             }
        return true;
    }
    
    
    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        if (mode == 1) {
            // create new file
            FileDialog fd = new FileDialog(this, "Choose where to save", FileDialog.SAVE);
            fd.setDirectory(System.getProperty("user.home"));
            fd.setFile("*.json");
            fd.setVisible(true);
            String filename = fd.getFile();
            if (filename == null) {
              continueBtn.setEnabled(false);
              filePathDisplay.setText("");
              System.out.println("You cancelled the choice");
            } else {
              continueBtn.setEnabled(true);
              String filePath = fd.getDirectory() + fd.getFile();
              finalP = filePath;
              System.out.println("You chose " + filePath);
              filePathDisplay.setText(filePath);
              
            JSONObject sales = new JSONObject();
            
            data = new JSONObject();
            data.put("sales", sales);
            
//            JSONObject salesx = data.getJSONObject("sales");
//            JSONObject sale2 = new JSONObject();
//            
//            sale2.put("mango", 0);
//            sale2.put("laici", 0);
//            sale2.put("stroberi", 0);
//            sale2.put("blackcurrant", 0);
//            sale2.put("tax", 0);
//            sale2.put("subtotal", 0);
//            sale2.put("totalprice", 0);
//            
//            sales.put(1, sale2);
//            data.put("sales", sales);
            data.put("current_sale_id", 0);
            System.out.println(data);
           
            saveChanges();
            
                this.setVisible(false);
                new Menu(this).setVisible(true);
            }
        } else {
            System.out.println("aa");
            // load the current file from directory
            File f = new File(finalP);
            if (f.exists()){
                 try
                {
                    InputStream is = new FileInputStream(finalP);
                    String jsonTxt = IOUtils.toString(is, "UTF-8");
                    JSONParser parser = new JSONParser();
                    Object obj = parser.parse(jsonTxt);
                    data = (JSONObject) obj;
                }    catch (Exception ex)  
                {
                    // insert code to run when exception occurs
                    JOptionPane.showMessageDialog(null, "Invalid data file.", "Oops", JOptionPane.ERROR_MESSAGE);
                }
                 
                current_sale_id = ((Long) data.get("current_sale_id")).intValue();
                System.out.println(current_sale_id);
                
                this.setVisible(false);
                new Menu(this).setVisible(true);
             }
        }

    }//GEN-LAST:event_continueBtnActionPerformed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnMouseClicked

    public int addSale(double totallaici, double totalstroberi, double totalmango, double totalblackcurrant, double tax, double totalprice, double finalprice, Calendar timer, int laici, int stroberi, int mango, int blackcurrant, int id) {
            
        JSONObject sales = (JSONObject) data.get("sales");
                
        JSONObject sale1 = new JSONObject();
        
        totallaici = laici*hausboom;
        totalstroberi = stroberi*hausboom;
        totalmango = mango*hausboom;
        totalblackcurrant= blackcurrant*hausboom;
        
        // Calculation
        totalprice  = totallaici+totalstroberi+totalmango+totalblackcurrant;
        tax = totalprice*0.15;
        finalprice = totalprice + tax;
        
        sale1.put("id", id);
        sale1.put("total_mango", totalmango);
        sale1.put("total_laici", totallaici);
        sale1.put("total_stroberi", totalstroberi);
        sale1.put("total_blackcurrant", totalblackcurrant);
        
        sale1.put("mango", mango);
        sale1.put("laici", laici);
        sale1.put("stroberi", stroberi);
        sale1.put("blackcurrant", blackcurrant);
        
        sale1.put("tax", tax);
        sale1.put("subtotal", totalprice);
        sale1.put("totalprice", finalprice);

        sale1.put("timer", timer.getTimeInMillis());
        sales.put(id, sale1);
        
        data.put("sales", sales);
        
        saveChanges();  
        
        return id;
    }
    
    public int addSale(double totallaici, double totalstroberi, double totalmango, double totalblackcurrant, double tax, double totalprice, double finalprice, Calendar timer, int laici, int stroberi, int mango, int blackcurrant) {
            
        JSONObject sales = (JSONObject) data.get("sales");
                
        JSONObject sale1 = new JSONObject();
        
        current_sale_id++;
        
        sale1.put("id", current_sale_id);
        sale1.put("total_mango", totalmango);
        sale1.put("total_laici", totallaici);
        sale1.put("total_stroberi", totalstroberi);
        sale1.put("total_blackcurrant", totalblackcurrant);
        
        sale1.put("mango", mango);
        sale1.put("laici", laici);
        sale1.put("stroberi", stroberi);
        sale1.put("blackcurrant", blackcurrant);
        
        sale1.put("tax", tax);
        sale1.put("subtotal", totalprice);
        sale1.put("totalprice", finalprice);

        sale1.put("timer", timer.getTimeInMillis());
        
        sales.put(current_sale_id, sale1);
        data.put("current_sale_id", current_sale_id);
        data.put("sales", sales);
        
        saveChanges();  
        
        return current_sale_id;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateImportClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton continueBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField filePathDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton locateFile;
    // End of variables declaration//GEN-END:variables
}