/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.adridanrakanrakan;

/**
 *
 * @author ayieb
 */
import java.awt.event.KeyEvent;
import java.util.*;
import java.text.*;
import java.lang.*;
import javax.swing.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.JSONValue;
import java.io.*;  
import java.util.logging.Level;
import java.util.logging.Logger;

public class ProductsClass extends javax.swing.JFrame {

    /**
     * Creates new form ProductsClass
     */
    public ProductsClass() {
        initComponents();
    }
    
    DecimalFormat df = new DecimalFormat ("0.00");
    
   
    double hausboom = 2.00;
    String  txtTax, txtFinalPrice,txtSubtotal ;
    double totallaici, totalmango, totalstroberi, totalblackcurrant, totalprice,tax,finalprice;
    int qtyLaici = 0, qtyMango = 0, qtyStroberi = 0, qtyBlackcurrant = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProduct = new javax.swing.JPanel();
        jLaiciButton = new javax.swing.JButton();
        jStrawberryButton = new javax.swing.JButton();
        jMangoButton = new javax.swing.JButton();
        jBlackcurrentButton = new javax.swing.JButton();
        jQtyPanel = new javax.swing.JPanel();
        jQtyLycheePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jQtyLaici = new javax.swing.JTextField();
        jClearLaici = new javax.swing.JButton();
        jqtyStrawberryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jQtyStroberi = new javax.swing.JTextField();
        jClearStroberi = new javax.swing.JButton();
        jQtyMangoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jQtyMango = new javax.swing.JTextField();
        jClearMango = new javax.swing.JButton();
        jQtyBlackcurrantPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jQtyBlackcurrent = new javax.swing.JTextField();
        jClearBlackcurrant = new javax.swing.JButton();
        jTaxLabel = new javax.swing.JLabel();
        jTotalTax = new javax.swing.JTextField();
        jSubtotalLabel = new javax.swing.JLabel();
        jSubtotal = new javax.swing.JTextField();
        jTotalPriceLabel = new javax.swing.JLabel();
        jTotalPrice = new javax.swing.JTextField();
        jReceiptPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReceipt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jSubmit = new javax.swing.JButton();
        jBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jProduct.setBackground(new java.awt.Color(255, 255, 255));
        jProduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));

        jLaiciButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/laici.png"))); // NOI18N
        jLaiciButton.setContentAreaFilled(false);
        jLaiciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLaiciButtonActionPerformed(evt);
            }
        });

        jStrawberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/stroberi.png"))); // NOI18N
        jStrawberryButton.setContentAreaFilled(false);
        jStrawberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStrawberryButtonActionPerformed(evt);
            }
        });

        jMangoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/pelam.png"))); // NOI18N
        jMangoButton.setContentAreaFilled(false);
        jMangoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMangoButtonActionPerformed(evt);
            }
        });

        jBlackcurrentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/anggot.png"))); // NOI18N
        jBlackcurrentButton.setContentAreaFilled(false);
        jBlackcurrentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlackcurrentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jProductLayout = new javax.swing.GroupLayout(jProduct);
        jProduct.setLayout(jProductLayout);
        jProductLayout.setHorizontalGroup(
            jProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLaiciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jStrawberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jMangoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jBlackcurrentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jProductLayout.setVerticalGroup(
            jProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMangoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStrawberryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLaiciButton, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jBlackcurrentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jQtyPanel.setBackground(new java.awt.Color(255, 255, 255));
        jQtyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));

        jQtyLycheePanel.setBackground(new java.awt.Color(0, 153, 255));
        jQtyLycheePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lychee:");

        jQtyLaici.setText("0");
        jQtyLaici.setEnabled(false);
        jQtyLaici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtyLaiciActionPerformed(evt);
            }
        });
        jQtyLaici.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQtyLaiciKeyTyped(evt);
            }
        });

        jClearLaici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/clear.png"))); // NOI18N
        jClearLaici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearLaiciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jQtyLycheePanelLayout = new javax.swing.GroupLayout(jQtyLycheePanel);
        jQtyLycheePanel.setLayout(jQtyLycheePanelLayout);
        jQtyLycheePanelLayout.setHorizontalGroup(
            jQtyLycheePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyLycheePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQtyLycheePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jClearLaici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jQtyLaici, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jQtyLycheePanelLayout.setVerticalGroup(
            jQtyLycheePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyLycheePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jQtyLycheePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jQtyLaici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClearLaici, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jQtyLaici.getAccessibleContext().setAccessibleName("");
        jQtyLaici.getAccessibleContext().setAccessibleDescription("");

        jqtyStrawberryPanel.setBackground(new java.awt.Color(0, 153, 255));
        jqtyStrawberryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Strawberry:");

        jQtyStroberi.setText("0");
        jQtyStroberi.setEnabled(false);
        jQtyStroberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtyStroberiActionPerformed(evt);
            }
        });
        jQtyStroberi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jQtyStroberiKeyTyped(evt);
            }
        });

        jClearStroberi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/clear.png"))); // NOI18N
        jClearStroberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearStroberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jqtyStrawberryPanelLayout = new javax.swing.GroupLayout(jqtyStrawberryPanel);
        jqtyStrawberryPanel.setLayout(jqtyStrawberryPanelLayout);
        jqtyStrawberryPanelLayout.setHorizontalGroup(
            jqtyStrawberryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jqtyStrawberryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jqtyStrawberryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jqtyStrawberryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jQtyStroberi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jqtyStrawberryPanelLayout.createSequentialGroup()
                        .addComponent(jClearStroberi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jqtyStrawberryPanelLayout.setVerticalGroup(
            jqtyStrawberryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jqtyStrawberryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jqtyStrawberryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQtyStroberi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClearStroberi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jQtyMangoPanel.setBackground(new java.awt.Color(0, 153, 255));
        jQtyMangoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mango:");

        jQtyMango.setText("0");
        jQtyMango.setEnabled(false);
        jQtyMango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtyMangoActionPerformed(evt);
            }
        });
        jQtyMango.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mangoInt(evt);
            }
        });

        jClearMango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/clear.png"))); // NOI18N
        jClearMango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearMangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jQtyMangoPanelLayout = new javax.swing.GroupLayout(jQtyMangoPanel);
        jQtyMangoPanel.setLayout(jQtyMangoPanelLayout);
        jQtyMangoPanelLayout.setHorizontalGroup(
            jQtyMangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyMangoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQtyMangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jQtyMangoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jQtyMango, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jQtyMangoPanelLayout.createSequentialGroup()
                        .addComponent(jClearMango)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jQtyMangoPanelLayout.setVerticalGroup(
            jQtyMangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyMangoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQtyMangoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQtyMango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jClearMango)
                .addContainerGap())
        );

        jQtyBlackcurrantPanel.setBackground(new java.awt.Color(0, 153, 255));
        jQtyBlackcurrantPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blackcurrant:");

        jQtyBlackcurrent.setText("0");
        jQtyBlackcurrent.setEnabled(false);
        jQtyBlackcurrent.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jQtyBlackcurrentInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jQtyBlackcurrent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jQtyBlackcurrentKeyPressed(evt);
            }
        });

        jClearBlackcurrant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/adridanrakanrakan/res/img/clear.png"))); // NOI18N
        jClearBlackcurrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBlackcurrantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jQtyBlackcurrantPanelLayout = new javax.swing.GroupLayout(jQtyBlackcurrantPanel);
        jQtyBlackcurrantPanel.setLayout(jQtyBlackcurrantPanelLayout);
        jQtyBlackcurrantPanelLayout.setHorizontalGroup(
            jQtyBlackcurrantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyBlackcurrantPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jQtyBlackcurrantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jQtyBlackcurrantPanelLayout.createSequentialGroup()
                        .addComponent(jClearBlackcurrant)
                        .addGap(56, 56, 56))
                    .addGroup(jQtyBlackcurrantPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jQtyBlackcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jQtyBlackcurrantPanelLayout.setVerticalGroup(
            jQtyBlackcurrantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyBlackcurrantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQtyBlackcurrantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQtyBlackcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClearBlackcurrant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTaxLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTaxLabel.setText("Tax:");

        jTotalTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTotalTax.setText("0.00");
        jTotalTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jTotalTax.setEnabled(false);

        jSubtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSubtotalLabel.setText("Subtotal:");

        jSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSubtotal.setText("0.00");
        jSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jSubtotal.setEnabled(false);

        jTotalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotalPriceLabel.setText("Total:");

        jTotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTotalPrice.setText("0.00");
        jTotalPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jTotalPrice.setEnabled(false);

        javax.swing.GroupLayout jQtyPanelLayout = new javax.swing.GroupLayout(jQtyPanel);
        jQtyPanel.setLayout(jQtyPanelLayout);
        jQtyPanelLayout.setHorizontalGroup(
            jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jQtyPanelLayout.createSequentialGroup()
                        .addComponent(jQtyLycheePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jqtyStrawberryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jQtyPanelLayout.createSequentialGroup()
                                .addComponent(jSubtotalLabel)
                                .addGap(6, 6, 6)
                                .addComponent(jSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jQtyPanelLayout.createSequentialGroup()
                                .addComponent(jTotalPriceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jQtyPanelLayout.createSequentialGroup()
                                .addComponent(jQtyMangoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jQtyBlackcurrantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jQtyPanelLayout.createSequentialGroup()
                        .addComponent(jTaxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTotalTax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jQtyPanelLayout.setVerticalGroup(
            jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQtyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jQtyPanelLayout.createSequentialGroup()
                        .addComponent(jQtyBlackcurrantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jQtyPanelLayout.createSequentialGroup()
                        .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jQtyMangoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jQtyLycheePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jqtyStrawberryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jQtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTaxLabel)
                            .addComponent(jTotalTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubtotalLabel)
                            .addComponent(jSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTotalPriceLabel))
                        .addGap(100, 100, 100))))
        );

        jReceiptPanel.setBackground(new java.awt.Color(255, 255, 255));
        jReceiptPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));

        jReceipt.setColumns(20);
        jReceipt.setRows(5);
        jReceipt.setDisabledTextColor(new java.awt.Color(0, 153, 255));
        jReceipt.setEnabled(false);
        jScrollPane1.setViewportView(jReceipt);

        jLabel5.setText("Receipt");

        javax.swing.GroupLayout jReceiptPanelLayout = new javax.swing.GroupLayout(jReceiptPanel);
        jReceiptPanel.setLayout(jReceiptPanelLayout);
        jReceiptPanelLayout.setHorizontalGroup(
            jReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReceiptPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jReceiptPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jReceiptPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(170, 170, 170))))
        );
        jReceiptPanelLayout.setVerticalGroup(
            jReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReceiptPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jSubmit.setText(" Submit");
        jSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jSubmit.setContentAreaFilled(false);
        jSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubmitMouseClicked(evt);
            }
        });
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jBack.setText("Back");
        jBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jBack.setContentAreaFilled(false);
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jQtyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jQtyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
                  
   
    private void jQtyStroberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtyStroberiActionPerformed
       
    }//GEN-LAST:event_jQtyStroberiActionPerformed

    private void jQtyMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtyMangoActionPerformed
   
    }//GEN-LAST:event_jQtyMangoActionPerformed
 
    private void jQtyLaiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtyLaiciActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jQtyLaiciActionPerformed

    private void jClearLaiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearLaiciActionPerformed
       jQtyLaici.setText("");
       jQtyLaici.setEnabled(false);
       qtyLaici = 0;
       calculateTotal();
        
    }//GEN-LAST:event_jClearLaiciActionPerformed

    private void jClearStroberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearStroberiActionPerformed
        jQtyStroberi.setText("");
       jQtyStroberi.setEnabled(false);
       qtyStroberi = 0;
       calculateTotal();
    }//GEN-LAST:event_jClearStroberiActionPerformed

    private void jClearMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearMangoActionPerformed
        jQtyMango.setText("");
       jQtyMango.setEnabled(false);
       qtyMango = 0;
       calculateTotal();
    }//GEN-LAST:event_jClearMangoActionPerformed

    private void jClearBlackcurrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBlackcurrantActionPerformed
        jQtyBlackcurrent.setText("");
       jQtyBlackcurrent.setEnabled(false);
       qtyBlackcurrant = 0;
       calculateTotal();
       
    }//GEN-LAST:event_jClearBlackcurrantActionPerformed
       //COUNT BLACKCURRANT QTY BASED ON CLICK
     
    private void jBlackcurrentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlackcurrentButtonActionPerformed
        //Enable Quantity Textfield
      qtyBlackcurrant = qtyBlackcurrant + 1;
      
      jQtyBlackcurrent.setEnabled(true);
      jQtyBlackcurrent.setText(String.valueOf(qtyBlackcurrant));
      calculateTotal();
    }//GEN-LAST:event_jBlackcurrentButtonActionPerformed

    private void jMangoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMangoButtonActionPerformed
        //Enable Quantity Textfield
      qtyMango = qtyMango + 1;
      
      jQtyMango.setEnabled(true);
      jQtyMango.setText(String.valueOf(qtyMango));
      calculateTotal();
    }//GEN-LAST:event_jMangoButtonActionPerformed

    private void jStrawberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStrawberryButtonActionPerformed
        //Enable Quantity Textfield
      qtyStroberi = qtyStroberi + 1;
      
      jQtyStroberi.setEnabled(true);
      jQtyStroberi.setText(String.valueOf(qtyStroberi));
      calculateTotal();
    }//GEN-LAST:event_jStrawberryButtonActionPerformed

    private void jLaiciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLaiciButtonActionPerformed
        //Enable Quantity Textfield
      qtyLaici = qtyLaici + 1;
      
      jQtyLaici.setEnabled(true);
      jQtyLaici.setText(String.valueOf(qtyLaici));
      calculateTotal();
    }//GEN-LAST:event_jLaiciButtonActionPerformed

    private void calculateTotal() {
        totallaici = qtyLaici*hausboom;
        totalstroberi = qtyStroberi*hausboom;
        totalmango = qtyMango*hausboom;
       totalblackcurrant= qtyBlackcurrant*hausboom;
        
        // Calculation
        totalprice  = totallaici+totalstroberi+totalmango+totalblackcurrant;
        tax = totalprice*0.15;
        finalprice = totalprice + tax;
        
       
        //Decimal Format
        txtTax = df.format(tax);
        txtSubtotal = df.format(totalprice);
        txtFinalPrice = df.format(finalprice);
        
        //Display in Text File
        jTotalTax.setText(txtTax);
        jSubtotal.setText(txtSubtotal);
        jTotalPrice.setText(txtFinalPrice);
    }
    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        
         // Read Input based on quantity
         calculateTotal();
        
        ///////////////////////////////////////
        //Reference Number
        //========================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat ("dd=MMM=yyy");
        Tdate.format(timer.getTime());
        
        
        JSONObject sale = new JSONObject();
        
        // 0 - laici
        // 1 - stroberi
        // 2 - mango
        // 3 - blackcurrant
        int[] products = {qtyLaici, qtyStroberi, qtyMango, qtyBlackcurrant};
        
        sale.put("products",  Arrays.toString(products));
        StringWriter out = new StringWriter();
        try {
            sale.writeJSONString(out);
        } catch (IOException ex) {
            Logger.getLogger(ProductsClass.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        String jsonText = out.toString();
        System.out.print(jsonText);
        
        //=========================================================
        jReceipt.append("\t Haus Boom Orders \n" 
                + "Reference:\t\t\t\t"
                +"\n===========================================\t"+
                    "\n===============================================\t"+
                "\nLaici:\t\t"+jQtyLaici.getText()+
                "\nStrawberry:\t\t"+jQtyStroberi.getText()+
                "\nMango:\t\t"+jQtyMango.getText()+
                "\nBlackcurrant:\t\t"+jQtyBlackcurrent.getText()+
                "\n================================================\t"+
                    "\nTax:\t\t"+txtTax+
                    "\nSub Total:\t\t"+txtSubtotal+
                    "\nTotal Price:\t\t"+txtFinalPrice+
                    "\n================================================\t"+
                    "\nDate: "+Tdate.format(timer.getTime())+
                        "\t\tTime: "+tTime.format(timer.getTime())+
                    "\n\n\t THANK YOU FOR SHOPPING WITH HAUS BOOM !");
        
        //Disable All Button after Submitted
        jClearLaici.setEnabled(false);
        jClearStroberi.setEnabled(false);
        jClearMango.setEnabled(false);
        jClearBlackcurrant.setEnabled(false);
        jSubmit.setEnabled(false);
        
        //Disable All Textfield after Submitted
        jQtyLaici.setEnabled(false);
        jQtyStroberi.setEnabled(false);
         jQtyMango.setEnabled(false);
        jQtyBlackcurrent.setEnabled(false);
        
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubmitMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jSubmitMouseClicked

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        new Menu().setVisible(true); dispose(); //go back to menu
    }//GEN-LAST:event_jBackMouseClicked

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBackActionPerformed

    private void jQtyLaiciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtyLaiciKeyTyped
         // Only input INT
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)){
          getToolkit().beep();
          evt.consume();
        } else if (!jQtyLaici.getText().equals("")) {
            qtyLaici = Integer.parseInt(jQtyLaici.getText());
            jQtyLaici.setText(String.valueOf(qtyLaici));
    
        }
    }//GEN-LAST:event_jQtyLaiciKeyTyped

    private void jQtyStroberiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtyStroberiKeyTyped
                // Only input INT
        char c = evt.getKeyChar();
        if( !(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)){
          getToolkit().beep();
          evt.consume();
        } else if (!jQtyStroberi.getText().equals("")) {
            int current = Integer.parseInt(jQtyStroberi.getText());
            jQtyStroberi.setText(String.valueOf(current));
         
        }
    }//GEN-LAST:event_jQtyStroberiKeyTyped

    private void mangoInt(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mangoInt
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)){
          getToolkit().beep();
          evt.consume();
        } else if (!jQtyMango.getText().equals("")) {
            qtyMango = Integer.parseInt(jQtyMango.getText());
            jQtyMango.setText(String.valueOf(qtyMango));
     
        }
        
    }//GEN-LAST:event_mangoInt

    private void jQtyBlackcurrentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQtyBlackcurrentKeyPressed
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)){
          getToolkit().beep();
          evt.consume();
        } else if (!jQtyBlackcurrent.getText().equals("")) {
            qtyBlackcurrant = Integer.parseInt(jQtyBlackcurrent.getText());
            jQtyBlackcurrent.setText(String.valueOf(qtyBlackcurrant));
        }
    }//GEN-LAST:event_jQtyBlackcurrentKeyPressed

    private void jQtyBlackcurrentInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jQtyBlackcurrentInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jQtyBlackcurrentInputMethodTextChanged
                       

                                         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JButton jBlackcurrentButton;
    private javax.swing.JButton jClearBlackcurrant;
    private javax.swing.JButton jClearLaici;
    private javax.swing.JButton jClearMango;
    private javax.swing.JButton jClearStroberi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLaiciButton;
    private javax.swing.JButton jMangoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jProduct;
    private javax.swing.JPanel jQtyBlackcurrantPanel;
    private javax.swing.JTextField jQtyBlackcurrent;
    private javax.swing.JTextField jQtyLaici;
    private javax.swing.JPanel jQtyLycheePanel;
    private javax.swing.JTextField jQtyMango;
    private javax.swing.JPanel jQtyMangoPanel;
    private javax.swing.JPanel jQtyPanel;
    private javax.swing.JTextField jQtyStroberi;
    private javax.swing.JTextArea jReceipt;
    private javax.swing.JPanel jReceiptPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jStrawberryButton;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTextField jSubtotal;
    private javax.swing.JLabel jSubtotalLabel;
    private javax.swing.JLabel jTaxLabel;
    private javax.swing.JTextField jTotalPrice;
    private javax.swing.JLabel jTotalPriceLabel;
    private javax.swing.JTextField jTotalTax;
    private javax.swing.JPanel jqtyStrawberryPanel;
    // End of variables declaration//GEN-END:variables
}
